### ISSUE TITLE
Need help in package deployment

### ISSUE THREAD

**Issue by austindsouza** [ctron/kura-examples#2]
Hi,

I have an use case where I need to create a table in JDBC when the OSGI package starts in Kura.
The sensor streamed data should be stored in that table for further analysis.

I have created a OSGI bundle which does the above requirements using SQL prepared statement to generate create table query, the only problem is that JDBC table name and its column names are hard-coded.
 
Is it possible to pass the table name and details in package deployment API's parameter and get the values so that to make table creation function as dynamic.

To upload the package I've used curl command as given below.

curl -i -X POST --cookie "JSESSIONID=1q1ayau5xchymwhbn2vltbgm2; HttpOnly" --user admin:admin -H "Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryPkbBNlWAKYcjXkgH" -F "uploadedFile=@/tmp/edge/hello_osgi.dp" -F "xsrfToken=58e5cc1c-3478-4794-a5b1-b1bdfb6cde02" http://localhost:8080/denali/file/deploy/upload

the package is uploaded successfully and I can see its status in Kura web UI.

 Could you please provide me any solutions for this.

Thanks & Regards,
Austin

**Comment by ctron** [comment]
I think you should ask this question in the Eclipse Kura project: https://projects.eclipse.org/projects/technology.kura/contact

**Comment by austindsouza** [comment]
OK @ctron 

Thanks!
